// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_character_id_ from "./routes/(platform)/character/[id].tsx";
import * as $_platform_characters from "./routes/(platform)/characters.tsx";
import * as $_platform_house from "./routes/(platform)/house.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $CharList from "./islands/CharList.tsx";
import * as $HouseFilter from "./islands/HouseFilter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/character/[id].tsx": $_platform_character_id_,
    "./routes/(platform)/characters.tsx": $_platform_characters,
    "./routes/(platform)/house.tsx": $_platform_house,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
    "./routes/logout.tsx": $logout,
  },
  islands: {
    "./islands/CharList.tsx": $CharList,
    "./islands/HouseFilter.tsx": $HouseFilter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
